# Generated by Django 5.1.5 on 2026-02-26 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.FloatField(help_text='Seconds')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta do Utilizador',
                'verbose_name_plural': 'Respostas dos Utilizadores',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progresso do Utilizador',
                'verbose_name_plural': 'Progressos dos Utilizadores',
            },
        ),
    ]
