# Generated by Django 5.1.5 on 2026-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='placement_test_completed',
            field=models.BooleanField(default=False),
        ),
    ]
