# Generated by Django 5.1.5 on 2026-02-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Painel de Analytics',
                'verbose_name_plural': 'Painel de Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quizzes.quizsession',),
        ),
    ]
