# Generated by Django 5.1.5 on 2026-03-02 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRankingArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo de Ranking Semanal',
                'verbose_name_plural': 'Arquivos de Ranking Semanal',
                'ordering': ['-week_end'],
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('xp_earned', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_entries', to=settings.AUTH_USER_MODEL)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rankings.weeklyrankingarchive')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('archive', 'user')},
            },
        ),
    ]
