# Generated by Django 5.1.5 on 2026-02-26 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_native', models.CharField(max_length=100)),
                ('word_portuguese', models.CharField(max_length=100)),
                ('pronunciation_audio', models.FileField(blank=True, null=True, upload_to='audio/words/')),
                ('difficulty', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('saudacoes', 'Saudações'), ('pronomes', 'Pronomes'), ('verbos', 'Verbos'), ('animais', 'Animais'), ('familia', 'Família'), ('numeros', 'Números'), ('cores', 'Cores'), ('cultura', 'Cultura'), ('natureza', 'Natureza'), ('corpo', 'Corpo Humano'), ('alimentos', 'Alimentos')], default='saudacoes', max_length=50)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palavra',
                'verbose_name_plural': 'Palavras',
                'ordering': ['language', 'difficulty', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Escolha Múltipla'), ('audio', 'Áudio'), ('fill_blank', 'Completar Frase'), ('translation', 'Tradução Direta')], default='multiple_choice', max_length=20)),
                ('difficulty', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('cultural_note', models.TextField(blank=True, default='')),
                ('timer_seconds', models.PositiveIntegerField(default=5)),
                ('xp_value', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='languages.language')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['language', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('total_makuta_earned', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='languages.language')),
                ('questions', models.ManyToManyField(blank=True, related_name='sessions', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Sessão de Quiz',
                'verbose_name_plural': 'Sessões de Quiz',
                'ordering': ['-started_at'],
            },
        ),
    ]
