# Generated by Django 5.1.5 on 2026-02-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='languages.language'),
        ),
        migrations.AddField(
            model_name='question',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quizzes.word'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('language', 'word_native')},
        ),
    ]
