# Generated by Django 5.1.5 on 2026-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="min_age",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
