# Generated by Django 5.1.5 on 2026-03-03 17:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_question_min_age"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpacedRepetitionCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ease_factor", models.FloatField(default=2.5)),
                ("interval", models.IntegerField(default=1)),
                ("repetitions", models.IntegerField(default=0)),
                (
                    "next_review",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
                ("last_quality", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sr_cards",
                        to="quizzes.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sr_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "next_review"],
                        name="quizzes_spa_user_id_acf2a4_idx",
                    )
                ],
                "unique_together": {("user", "question")},
            },
        ),
    ]
