# Generated by Django 5.1.5 on 2026-02-26 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('xp_required', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medalha',
                'verbose_name_plural': 'Medalhas',
                'ordering': ['xp_required'],
            },
        ),
        migrations.CreateModel(
            name='UserXPLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_gained', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('quiz', 'Quiz'), ('streak', 'Streak Bonus'), ('challenge', 'Desafio Diário'), ('level_up', 'Subida de Nível')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de XP',
                'verbose_name_plural': 'Logs de XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gamification.badge')),
            ],
            options={
                'verbose_name': 'Medalha do Utilizador',
                'verbose_name_plural': 'Medalhas dos Utilizadores',
            },
        ),
    ]
